export const narrativeScenes = [
  {
    id: "field-collection",
    index: "SCENE 02 / FIELD COLLECTION",
    name: "林径采样",
    title: "在林径停下，把问题写进一页标本记录。",
    description: "从一株草药、一次观察开始，把正在学习的内容整理成可以继续追问的线索。",
    actionLabel: "进入三条学习线索",
    target: "#reading-rooms",
    imageSrc: "/manus-storage/scene-02-forest-collection_33168548.jpg",
    imageAlt: "药草研究员在晨雾山林中蹲下，记录并采集药草样本",
  },
  {
    id: "cabin-archive",
    index: "SCENE 03 / CABIN ARCHIVE",
    name: "林屋整理",
    title: "把散落的观察，整理为可以继续翻阅的档案。",
    description: "在窗边、药瓶与笔记之间，让中药学、AI、代码和实践逐渐形成自己的结构。",
    actionLabel: "翻开身份与能力档案",
    target: "#profile",
    imageSrc: "/manus-storage/scene-03-cabin-archive_0ef11be4.jpg",
    imageAlt: "药草研究员在林屋书桌前整理笔记与植物标本",
  },
  {
    id: "night-tactics",
    index: "SCENE 04 / NIGHT TACTICS",
    name: "夜间战术",
    title: "夜色落下，继续把想法做成可运行的实践。",
    description: "从资料桌上的推演到网页里的实际操作，作品是把问题带进真实场景的一种方式。",
    actionLabel: "查看作品样本",
    target: "#work",
    imageSrc: "/manus-storage/scene-04-night-tactics_81f015d0.jpg",
    motionVideoSrc: "/manus-storage/t04-night-tactics-only_dbb32797.mp4",
    imageAlt: "月夜山林中，药草研究员在油灯旁查看笔记与战术模型",
  },
  {
    id: "lamp-archive",
    index: "SCENE 05 / LAMP ARCHIVE",
    name: "灯下归档",
    title: "灯下收束一天的记录，也为下一段对话留出位置。",
    description: "持续学习、持续整理、持续向前。愿每一次记录都能成为下一次实践的起点。",
    actionLabel: "写一封信给我",
    target: "#contact",
    imageSrc: "/manus-storage/scene-05-lamp-archive_b7585421.jpg",
    motionVideoSrc: "/manus-storage/t05-lamp-archive-final_8dfb0e90.mp4",
    imageAlt: "药草研究员在温暖油灯旁整理标本袋，窗外是傍晚森林",
  },
] as const;

export type NarrativeScene = (typeof narrativeScenes)[number];
